### PR TITLE
"Improve" metadata class by making it simpler

### PR DESCRIPTION
**Pull request by qubixes**
I added an __init__ function so that a metadata object is always linked to a single item. This means that the convenience of supplying a list is gone and needs to be done at another level.

I also changed the behavior of the update/set function. I think it is more intuitive if the set function always removes the data regardless if it there were already key/value pairs.

Feedback is appreciated!

### CODE REVIEW

**Comment by qubixes** [comment]
I forgot to mention, I haven't tested the code yet, so it should probably be a draft PR!

**Comment by chStaiger** [comment]
I added the import of Optional and I added a property that displays the current metadata in human readable form.

**Comment by chStaiger** [comment]
Tested and approved!

**Comment by qubixes** [comment]
Feel free to merge if satisfied!

**Comment by chStaiger** [comment]
I like the `__iter__` next to the `__repr__`. they are both very handy!!!

**Pull request merged**
